[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

solc = "0.8.24"

optimizer = true
optimizer_runs = 10000

via_ir = true

fs_permissions = [
    { access = "read-write", path = "./" }
]

gas_reports = ["*"]

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 32
fail_on_revert = false