name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  check:
  name: Foundry project
  runs-on: ubuntu-latest


permissions:
  contents: read

steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      persist-credentials: false
      submodules: recursive

  - name: Install Foundry
    uses: foundry-rs/foundry-toolchain@v1

  - name: Show Forge version
    run: forge --version

  - name: Run Forge fmt
    run: forge fmt --check

  - name: Run Forge build
    run: forge build

  - name: Run Forge tests
    run: forge test -vv